spring:
  datasource:
    url: jdbc:sqlserver://myserver3.database.windows.net:1433;database=mydb1;user=springtech@myserver3;password={your_password_here};encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: springtech
    password: Alfahad@9721
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      dialect : org.hibernate.dialect.SQLServer2012Dialect
server:
  port: 9199


